import Head from "next/head";
import Image from "next/image";
import mongoose from "mongoose";
import connectMongo from "../utils/connectMongo";
import quranCollection from "../models/quranCollection";
import styles from "../styles/Home.module.css";
import BrandBar from "../components/BrandBar";
import Product from "../components/Product";
import ShoppingCart from "../components/ShoppingCart";
import $ from "jquery";
import React, { useEffect, useState } from "react";
import Router from "next/router";
import Link from "next/link";
import { Checkout } from "../checkout";
import CustomerBilling from "../components/BillingForm";

export default function Home({ backendData }) {
  const [cartItems, setCartItems] = useState([]);

  function toggleProductContainer() {
    const productContainer = $(".product_Container");
    const cartContainer = $(".cart_Container");
    $(productContainer).toggleClass("col-md-8");
    $(cartContainer).toggleClass("hidden");
  }
  function addProductToCart(e, product) {
    setCartItems((prev) => {
      return [...prev, product];
    });
  }
  function removeItem(e, id) {
    setCartItems((prev) => {
      return cartItems.filter((item, index) => {
        return id !== index;
      });
    });
  }
  function clearCart() {
    setCartItems([]);
  }
  function checkout(billingForm) {
    console.log("cartItems: ", cartItems);
    const lineItemsArray = cartItems.map((value) => {
      return { price: value.strip_pid, quantity: value.quantity };
    });
    Checkout({ lineItems: lineItemsArray });
  }
  // function viewBillignForm(){
  //   customer_billing
  // }
  // function viewCart() {
  //   console.log("cartItems: ", cartItems);
  //   // Router.push({pathname: "/cart", query: {cartItems:
  //   // JSON.stringify(cartItems)}});
  //   const lineItemsArray = cartItems.map((value) => {
  //     return { price: value.strip_pid, quantity: value.quantity };
  //   });
  //   checkout({ lineItems: lineItemsArray });
  // }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BrandBar
        cartIconClick={toggleProductContainer}
        cartItemCount={cartItems.length}
      />
      <div className="container-fluid">
        <div className="row d-flex flex-row product_cart_Container mt-5">
          <div className="col-md-4 order-md-2 cart_Container border border-primary hidden">
            <ShoppingCart
              cartItems={cartItems}
              onRemoveItem={removeItem}
              clearCart={clearCart}
              // viewBillingForm={}
            />
          </div>
          <div className=" order-md-1  product_Container">
            <div className="row">
              {backendData.map((product, index) => {
                return (
                  <Product
                    key={index}
                    id={index}
                    onAdd={addProductToCart}
                    itemName={product.itemName}
                    totalPrice={product.deliveryCost + product.value}
                    strip_pid={product.strip_pid}
                    text={
                      "This item contains a box of 16 Price: £" +
                      (product.deliveryCost + product.value)
                    }
                    mySrc="https://i.ebayimg.com/images/g/MrAAAOSwjNFfR4al/s-l500.png"
                  />
                );
              })}
            </div>
          </div>
        </div>
      </div>
      <section id="customer_billing">
        <CustomerBilling checkout={checkout} />
      </section>
    </div>
  );
}

export const getServerSideProps = async () => {
  try {
    console.log("CONNECTING TO MONGO");
    await connectMongo();
    console.log("CONNECTED TO MONGO");

    console.log("FETCHING DOCUMENTS");
    const docs = await quranCollection.find({});
    console.log("FETCHED DOCUMENTS");
    console.log(docs);

    return {
      props: {
        backendData: JSON.parse(JSON.stringify(docs)),
      },
    };
  } catch (error) {
    console.log(error);
    return { notFound: true };
  }
};
